export const language = [{ //Словарь для локализации TODO:Redux
    questions: 'Вопросы',
    about: 'О нас',
    сontacts: 'Контакты',
    search: 'Поиск',
    sections: 'Разделы',
    programming:'Программирование',
    other: 'Остальные вопросы',
    cooking: 'Готовка',
    diy: 'Сделай сам',
    lifehacks: 'Лайфхаки',
    topicks: 'Волнующие народ темы',
    ask: 'Задать вопрос',
    related:'Связанные теги',
    mail: 'Почта',
    sign: 'Войти',
    register: 'Регистрация'
  },
  {
    questions: 'Questions',
    about: 'About us',
    сontacts: 'Contacts',
    search: 'Search',
    sections: 'Sections',
    programming:'Programming',
    other: 'Other help',
    cooking: 'Cooking',
    diy: 'DIY',
    lifehacks: 'Lifehacks',
    topicks: 'Topics of concern to the people',
    ask: 'Ask question',
    related:'Related Tags',
    mail: 'Gmail',
    sign: 'Sign In',
    register: 'Registration'
  }]